### ISSUE TITLE
Countdown timer starts with 00:00 after 24 hours

### ISSUE THREAD

**Issue by a-tokarev** [michaelvillar/timer-app#57]
![timer](https://user-images.githubusercontent.com/32895328/69398399-1c56da00-0cfb-11ea-85fb-22ef299311b0.png)

**Issue:** when the main timer (the black one) is set to more than 24 hours, the coundown timer (the red one) resets and starts counting up from 00:00 (see the screenshot). Even if this doesn't break the work of the timer, this is confusing.

**Suggestion:** remove the countdown timer's 24-hour display limit and let it display time intervals exceeding 24 hours, for example 32:24.

**Comment by karbassi** [comment]
The RED is the current time (and since your system is set to use `24-Hour Time`, it displays that way). The RED is also relative to what time it'll be once the timer runs out.

I ran the same example at 22:27 (10:29 PM) and it showed the following.

![Screen Shot 2020-04-09 at 22 27 57](https://user-images.githubusercontent.com/17738/78959799-a8eb1480-7ab1-11ea-83b1-89e520e6a735.png)
![Screen Shot 2020-04-09 at 22 28 18](https://user-images.githubusercontent.com/17738/78959806-abe60500-7ab1-11ea-9562-f06fe8cb9321.png)
