### ISSUE TITLE
elementary clone: Math issues

### ISSUE THREAD

**Issue by marbetschar** [michaelvillar/timer-app#59]
Hi Michael,

Thanks again for providing the design for the elementary clone of your Timer App! I made quite some progress, but right now I'm struggling with the math part.

If you have some time, it would be awesome if you can tell me what the following lines exactly do. 
My main question here is: What exactly are `location.x`, `location.y`, `center.x` and `center.y`?:

https://github.com/michaelvillar/timer-app/blob/b877c37a776567bc606bb332c48a579a51ca84e6/Timer/MVClockView.swift#L627-L635

I tried  to implement the logic, but for some reason the arrow item jumps straight to 6 o'clock:

![Timer-Glitch](https://user-images.githubusercontent.com/392542/73701160-ed8cb500-46e8-11ea-8136-91b5e830fddf.gif)

Here's how I tried to implement the functionality:

https://github.com/marbetschar/timer/blob/63a2169922ebc3a3fc7ee88d7a886fbf57c55ce7/src/Widgets/Arrow.vala#L78-L97

**Comment by marbetschar** [comment]
Seems like the underlying issue is a difference in the coordinate system used to position the elements. Under Linux (GTK) the origin seems to be the top-left corner, wherelse under macOS (Cocoa) the origin seems to be the lower-left corner - so the y-Axis behaves different.

That said, I was able to fix most of the calculation issues. But I'm still unable to wrap my head around the mentioned `location.x`, `location.y`, `center.x` and `center.y` values. What do they actually represent?

**Comment by robinstewart** [comment]
Looking at the code I assume that `location` is the (x,y) coordinates of the cursor, and `center` is the (x,y) coordinates of the center of the clock circle.

So `location.x - center.x` is the horizontal distance to the center, and `location.y - center.y` is the vertical distance. Those go into `atan(opp/adj)` to get an angle.

I may be missing something, but dividing by `center.x` and `center.y` in these lines looks like a bug to me:
```
 let dx = (location.x - center.x) / center.x 
 let dy = (location.y - center.y) / center.y 
```
It's not an issue in the current app if `center.x == center.y` (i.e. the clock is equal distance from the top and left) because the ratio `dy / dx` is unaffected by the rogue divides. If the clock were _not_ in the center of the view, I suspect you would see some skewing of the angle calculation.

**Comment by marbetschar** [comment]
@robinstewart thank you very much for your feedback! I finally found the issue: After hours of searching and testing it turned out I missed a simple `- PI / 2`.... 🤦‍♂️️

Now it works:
![Mit-Pfeil](https://user-images.githubusercontent.com/392542/73791982-a8798900-47a3-11ea-8413-d03f316a6e3e.gif)
